### ISSUE TITLE
Can I convert to .m4a

### ISSUE THREAD

**Issue by dr-suunta** [1n0r1/monster-siren-download#3]
Can you help me on the code? Instead convert to .flac or mp.3 Can I change it to .m4a? 

Thx

**Comment by 1n0r1** [comment]
Sure, the easy and quickest way is to have a seperate conversion script that do the convert after you have run the original script to download mp3 and flac. For the conversion script, you can use the same library I used, pydub, and do something like this. Here is a script that iterate through all the mp3 and flac file in the current directory and convert them to .m4a

```python
import os
import glob

from pydub import AudioSegment

# Output folder
output_folder = './MonsterSirenM4A'

# Get list of all mp3 and flac files in current dir
mp3_files = glob.glob("./**/*.mp3", recursive=True)
flac_files = glob.glob("./**/*.flac", recursive=True)
all_audio_files = mp3_files + flac_files

for audio_file in all_audio_files:
    # Figure out the file path to export to
    relative_path = os.path.relpath(audio_file)
    file_name_without_extension = os.path.splitext(relative_path)[0]
    output_path = os.path.join(output_folder, f"{file_name_without_extension}.m4a")
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    song = AudioSegment.from_file(audio_file) # load file
    song.export(output_path, format="ipod") # export to m4a

```
The problem is metadata won't work this way, as the formatting is different. You can look into this api and modify the original script to export to m4a, but I won't bother doing that as mp3 and flac is more universal (m4a/mp4 metadata only works with iTunes)
https://mutagen.readthedocs.io/en/latest/api/mp4.html
If do you want help also on the metadata part I would be happy to help.
